name = "StringEncodings"
uuid = "69024149-9ee7-55f6-a4c4-859efe599b68"
repo = "https://github.com/JuliaStrings/StringEncodings.jl.git"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
BinaryProvider = "0.4.1, 0.5"
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
